package model

import (
	"github.com/futurehomeno/fimpgo"
	"github.com/mitchellh/mapstructure"
	"time"
)

const (
	MsgPayloadFimp         = 0
	MsgPayloadJson         = 1
	MsgPayloadNone         = 2
	MsgPayloadBinary       = 3 // binary format like image,video , etc
	MsgPayloadBinaryJson   = 4 // binary encoded json
	MsgPayloadBinaryString = 5 // binary encoded string

	PayloadObjectTypeNone   = 0
	PayloadObjectTypeString = 1
	PayloadObjectTypeJson   = 2
)

type MsgPipeline chan Message

type FlowRunner func(ReactorEvent)

// Message is message that is sent from one node to another. Mostly generated by reactor node and passed throughout a flow.
type Message struct {
	AddressStr    string // any address string , for example : http address, mqtt address, etc.
	PayloadType   byte
	Address       fimpgo.Address     // fimp specific . Should be removed in the future . Legacy fimp field
	Payload       fimpgo.FimpMessage // fimp specific . Should be removed in the future . Legacy fimp field
	RawPayload    []byte             // raw array of bytes
	ObjectPayload any                // parsed or processed payload , for example json object , map , etc.
	ObjectType    byte               // type of payload , for example json , map , etc.
	Header        map[string]string
	CancelOp      bool // if true , listening end should close all operations
	RequestId     int64
	Origin        string
}

func (msg *Message) PayloadMsgToStruct(targetVar interface{}) {
	if msg.Payload.ValueType == fimpgo.VTypeObject {
		mapstructure.Decode(msg.Payload.Value, targetVar)
	}
}

// ReactorEvent is generated by reactor node , like Trigger , TimeTrigger , etc. Used only in flow runner.
type ReactorEvent struct {
	Msg              Message
	Err              error
	TransitionNodeId NodeID
	SrcNodeId        NodeID
}

type Setting struct {
	Value       interface{}
	ValueType   string // only simple types supported - int,string,float,bool
	Description string `json:"omitempty"` // Human readable description
	InitVar     bool   `json:"omitempty"` // If set , flow will init variable during startup
	TVarSType   string `json:"omitempty"` // Target variable storage type - mem_local, disk_local,disk_global
	TVarPType   string `json:"omitempty"` // Target variable payload type - int , string , float , bool
}

func (s *Setting) String() string {
	r, _ := s.Value.(string)
	return r
}

type FlowMeta struct {
	Id                string // Instance id . Is different for every instance
	ClassId           string // Class id , all instances share the same ClassId
	Author            string
	Version           int
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Name              string
	Group             string
	Description       string
	Nodes             []MetaNode
	Settings          map[string]Setting
	IsDisabled        bool
	IsDefault         bool   // default flows are read only and can't be deleted
	ParallelExecution string // keep_first , keep_last , parallel
}

const (
	SIGNAL_STOP                = 1
	SIGNAL_TERMINATE_WAITING   = 2 // Signal to terminate all waiting nodes but not trigger nodes
	ParallelExecutionKeepFirst = "keep_first"
	ParallelExecutionKeepLast  = "keep_last"
	ParallelExecutionParallel  = "parallel"
)

type FlowOperationalContext struct {
	FlowMeta                    *FlowMeta
	FlowId                      string
	IsFlowRunning               bool
	State                       string
	TriggerControlSignalChannel chan int // the channel should be used to stop all waiting nodes .
	NodeControlSignalChannel    chan int
	NodeIsReady                 chan bool // Flow should notify message router when next node is ready to process new message .
	StoragePath                 string
	ExtLibsDir                  string
}

type FlowStatsReport struct {
	CurrentNodeId          NodeID
	CurrentNodeLabel       string
	NumberOfNodes          int
	NumberOfTriggers       int
	NumberOfActiveTriggers int
	NumberOfActiveSubflows int
	State                  string
	StartedAt              time.Time
	WaitingSince           time.Time
	LastExecutionTime      int64
}
